http:
  routers:
    everafter:
      entryPoints:
        - web
      rule: PathPrefix(`/`)
      service: everafter
  services:
    everafter:
      loadBalancer:
        servers:
          # Fargate containers in one task share the task network namespace.
          - url: http://127.0.0.1:8000
